title: "History of botting and its impact"
author:
  name: "Unbotify Team @ Denuvo"
bio: "Denuvo by Irdeto's Unbotify Team is located in Salzburg, Austria. Its mission is to detect botting attempts and provide evidence for best-in-class anti-cheat solutions employed by global gaming customers."
remote_theme: jekyll/minima@v2.5.2

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
      image: https://denuvosoftwaresolutions.github.io/botting-history/denuvo-by-irdeto.png

header_pages:
  -

minima:
  # generate social links in footer
  social_links:
    twitter: gamingatdenuvo
    github:  denuvosoftwaresolutions
    linkedincompany: denuvo-gmbh

plugins:
  - jekyll-default-layout
  - jekyll-remote-theme
  - jekyll-optional-front-matter
